-- app_scheme_registry seed, generated from Icon Pack Studio's
-- device-verified URL scheme database (src/urlSchemes.js).
-- confidence: 'verified' = launched correct app on real device (iOS 26).
insert into app_scheme_registry (app_key, display_name, url_scheme, is_native_apple, confidence)
values
  ('phone', 'Phone', 'mobilephone://', true, 'verified'),
  ('messages', 'Messages', 'messages://', true, 'verified'),
  ('mail', 'Mail', 'message://', true, 'verified'),
  ('photos', 'Photos', 'photos-redirect://', true, 'verified'),
  ('settings', 'Settings', 'App-prefs://', true, 'verified'),
  ('maps', 'Maps', 'maps://', true, 'verified'),
  ('music', 'Music', 'music://', true, 'verified'),
  ('calendar', 'Calendar', 'calshow://', true, 'verified'),
  ('clock', 'Clock', 'clock-alarm://', true, 'verified'),
  ('notes', 'Notes', 'mobilenotes://', true, 'verified'),
  ('reminders', 'Reminders', 'x-apple-reminderkit://', true, 'verified'),
  ('weather', 'Weather', 'weather://', true, 'verified'),
  ('calculator', 'Calculator', 'calc://', true, 'medium'),
  ('wallet', 'Wallet', 'shoebox://', true, 'verified'),
  ('health', 'Health', 'x-apple-health://', true, 'verified'),
  ('app-store', 'App Store', 'itms-apps://', true, 'verified'),
  ('podcasts', 'Podcasts', 'podcasts://', true, 'verified'),
  ('facetime', 'FaceTime', 'facetime://', true, 'verified'),
  ('files', 'Files', 'shareddocuments://', true, 'verified'),
  ('home', 'Home', 'x-hm://', true, 'medium'),
  ('books', 'Books', 'ibooks://', true, 'verified'),
  ('fitness', 'Fitness', 'fitnessapp://', true, 'verified'),
  ('find-my', 'Find My', 'findmy://', true, 'medium'),
  ('shortcuts', 'Shortcuts', 'shortcuts://', true, 'high'),
  ('voice-memos', 'Voice Memos', 'voicememos://', true, 'medium'),
  ('stocks', 'Stocks', 'stocks://', true, 'medium'),
  ('news', 'News', 'applenews://', true, 'medium'),
  ('apple-tv', 'Apple TV', 'videos://', true, 'medium'),
  ('contacts', 'Contacts', 'contact://', true, 'medium'),
  ('instagram', 'Instagram', 'instagram://', false, 'verified'),
  ('x', 'X', 'twitter://', false, 'verified'),
  ('facebook', 'Facebook', 'fb://', false, 'verified'),
  ('tiktok', 'TikTok', 'snssdk1128://', false, 'verified'),
  ('snapchat', 'Snapchat', 'snapchat://', false, 'verified'),
  ('whatsapp', 'WhatsApp', 'whatsapp://', false, 'verified'),
  ('telegram', 'Telegram', 'tg://', false, 'verified'),
  ('messenger', 'Messenger', 'fb-messenger://', false, 'verified'),
  ('threads', 'Threads', 'barcelona://', false, 'verified'),
  ('reddit', 'Reddit', 'reddit://', false, 'verified'),
  ('pinterest', 'Pinterest', 'pinterest://', false, 'high'),
  ('linkedin', 'LinkedIn', 'linkedin://', false, 'high'),
  ('discord', 'Discord', 'discord://', false, 'verified'),
  ('signal', 'Signal', 'sgnl://', false, 'medium'),
  ('wechat', 'WeChat', 'weixin://', false, 'high'),
  ('viber', 'Viber', 'viber://', false, 'high'),
  ('line', 'Line', 'line://', false, 'high'),
  ('tumblr', 'Tumblr', 'tumblr://', false, 'medium'),
  ('bereal', 'BeReal', 'bereal://', false, 'medium'),
  ('clubhouse', 'Clubhouse', 'clubhouse://', false, 'medium'),
  ('youtube', 'YouTube', 'youtube://', false, 'verified'),
  ('netflix', 'Netflix', 'nflx://', false, 'verified'),
  ('spotify', 'Spotify', 'spotify://', false, 'verified'),
  ('prime-video', 'Prime Video', 'aiv://', false, 'medium'),
  ('disney', 'Disney+', 'disneyplus://', false, 'medium'),
  ('hulu', 'Hulu', 'hulu://', false, 'medium'),
  ('max', 'Max', 'hbomax://', false, 'medium'),
  ('twitch', 'Twitch', 'twitch://', false, 'verified'),
  ('soundcloud', 'SoundCloud', 'soundcloud://', false, 'high'),
  ('shazam', 'Shazam', 'shazam://', false, 'high'),
  ('audible', 'Audible', 'audible://', false, 'medium'),
  ('crunchyroll', 'Crunchyroll', 'crunchyroll://', false, 'medium'),
  ('plex', 'Plex', 'plex://', false, 'medium'),
  ('vlc', 'VLC', 'vlc://', false, 'medium'),
  ('steam', 'Steam', 'steam://', false, 'medium'),
  ('playstation', 'PlayStation', 'playstationapp://', false, 'medium'),
  ('roblox', 'Roblox', 'roblox://', false, 'medium'),
  ('kindle', 'Kindle', 'kindle://', false, 'medium'),
  ('goodreads', 'Goodreads', 'goodreads://', false, 'medium'),
  ('gmail', 'Gmail', 'googlegmail://', false, 'verified'),
  ('chrome', 'Chrome', 'googlechrome://', false, 'verified'),
  ('google', 'Google', 'google://', false, 'high'),
  ('google-maps', 'Google Maps', 'comgooglemaps://', false, 'verified'),
  ('google-drive', 'Google Drive', 'googledrive://', false, 'high'),
  ('google-photos', 'Google Photos', 'googlephotos://', false, 'high'),
  ('google-docs', 'Google Docs', 'googledocs://', false, 'medium'),
  ('google-sheets', 'Google Sheets', 'googlesheets://', false, 'medium'),
  ('gemini', 'Gemini', 'google-gemini://', false, 'medium'),
  ('chatgpt', 'ChatGPT', 'chatgpt://', false, 'verified'),
  ('claude', 'Claude', 'claude://', false, 'medium'),
  ('notion', 'Notion', 'notion://', false, 'verified'),
  ('slack', 'Slack', 'slack://', false, 'verified'),
  ('zoom', 'Zoom', 'zoomus://', false, 'verified'),
  ('teams', 'Teams', 'msteams://', false, 'high'),
  ('outlook', 'Outlook', 'ms-outlook://', false, 'high'),
  ('dropbox', 'Dropbox', 'dbapi-1://', false, 'medium'),
  ('evernote', 'Evernote', 'evernote://', false, 'medium'),
  ('todoist', 'Todoist', 'todoist://', false, 'medium'),
  ('trello', 'Trello', 'trello://', false, 'medium'),
  ('asana', 'Asana', 'asana://', false, 'medium'),
  ('canva', 'Canva', 'canva://', false, 'medium'),
  ('figma', 'Figma', 'figma://', false, 'medium'),
  ('github', 'GitHub', 'github://', false, 'medium'),
  ('1password', '1Password', 'onepassword://', false, 'medium'),
  ('duolingo', 'Duolingo', 'duolingo://', false, 'medium'),
  ('paypal', 'PayPal', 'paypal://', false, 'verified'),
  ('venmo', 'Venmo', 'venmo://', false, 'high'),
  ('cash-app', 'Cash App', 'cashme://', false, 'medium'),
  ('google-pay', 'Google Pay', 'gpay://', false, 'medium'),
  ('paytm', 'Paytm', 'paytm://', false, 'high'),
  ('phonepe', 'PhonePe', 'phonepe://', false, 'high'),
  ('wise', 'Wise', 'wise://', false, 'medium'),
  ('revolut', 'Revolut', 'revolut://', false, 'medium'),
  ('coinbase', 'Coinbase', 'coinbase://', false, 'medium'),
  ('binance', 'Binance', 'binance://', false, 'medium'),
  ('robinhood', 'Robinhood', 'robinhood://', false, 'medium'),
  ('amazon', 'Amazon', 'com.amazon.mobile.shopping://', false, 'verified'),
  ('ebay', 'eBay', 'ebay://', false, 'high'),
  ('etsy', 'Etsy', 'etsy://', false, 'medium'),
  ('aliexpress', 'AliExpress', 'aliexpress://', false, 'medium'),
  ('flipkart', 'Flipkart', 'flipkart://', false, 'high'),
  ('shein', 'Shein', 'shein://', false, 'medium'),
  ('temu', 'Temu', 'temu://', false, 'medium'),
  ('myntra', 'Myntra', 'myntra://', false, 'medium'),
  ('uber-eats', 'Uber Eats', 'ubereats://', false, 'high'),
  ('doordash', 'DoorDash', 'doordash://', false, 'medium'),
  ('zomato', 'Zomato', 'zomato://', false, 'high'),
  ('swiggy', 'Swiggy', 'swiggy://', false, 'high'),
  ('starbucks', 'Starbucks', 'starbucks://', false, 'medium'),
  ('mcdonald-s', 'McDonald''s', 'mcdonalds://', false, 'medium'),
  ('uber', 'Uber', 'uber://', false, 'verified'),
  ('lyft', 'Lyft', 'lyft://', false, 'high'),
  ('airbnb', 'Airbnb', 'airbnb://', false, 'high'),
  ('booking', 'Booking', 'booking://', false, 'medium'),
  ('expedia', 'Expedia', 'expedia://', false, 'medium'),
  ('tripadvisor', 'TripAdvisor', 'tripadvisor://', false, 'medium'),
  ('waze', 'Waze', 'waze://', false, 'high'),
  ('strava', 'Strava', 'strava://', false, 'high'),
  ('nike', 'Nike', 'nikeplus://', false, 'medium'),
  ('fitbit', 'Fitbit', 'fitbit://', false, 'medium'),
  ('myfitnesspal', 'MyFitnessPal', 'mfp://', false, 'medium'),
  ('headspace', 'Headspace', 'headspace://', false, 'medium'),
  ('calm', 'Calm', 'calm://', false, 'medium'),
  ('tinder', 'Tinder', 'tinder://', false, 'high'),
  ('bumble', 'Bumble', 'bumble://', false, 'medium'),
  ('hinge', 'Hinge', 'hinge://', false, 'medium'),
  ('nordvpn', 'NordVPN', 'nordvpn://', false, 'medium'),
  ('speedtest', 'Speedtest', 'speedtest://', false, 'medium'),
  ('firefox', 'Firefox', 'firefox://', false, 'high'),
  ('arc', 'Arc', 'arc://', false, 'medium')
on conflict (app_key) do update set
  display_name = excluded.display_name,
  url_scheme = excluded.url_scheme,
  is_native_apple = excluded.is_native_apple,
  confidence = excluded.confidence;
