// Generates a .scriptable file — a live, theme-matched widget for the free
// Scriptable app (App Store id 1405459188). Unlike the static photo widgets,
// this one shows real time, date, and battery, styled from the pack palette.
import { shade } from './svg.js';

const sanitize = (s) => s.replace(/[^\w\- ]/g, '').trim().replace(/\s+/g, '-') || 'pack';

export function scriptableWidget(pack) {
  const s = pack.style;
  const c1 = s.c1;
  const c2 = s.bgType === 'solid' ? shade(s.c1, -0.35) : (s.c2 ?? s.c1);
  const fg = s.glyphColor;
  const dim = 0.65;

  const script = `// ${pack.name} — live widget
// Generated by Icon Pack Studio. Install: Scriptable app -> add this script,
// then long-press Home Screen -> add a Scriptable widget -> choose it.
const w = new ListWidget()
w.setPadding(18, 18, 18, 18)

const g = new LinearGradient()
g.colors = [new Color(${JSON.stringify(c1)}), new Color(${JSON.stringify(c2)})]
g.locations = [0, 1]
w.backgroundGradient = g

const time = w.addDate(new Date())
time.applyTimeStyle()
time.font = Font.boldSystemFont(config.widgetFamily === "small" ? 32 : 40)
time.textColor = new Color(${JSON.stringify(fg)})
time.minimumScaleFactor = 0.5

w.addSpacer(4)

const date = w.addDate(new Date())
date.applyDateStyle()
date.font = Font.mediumSystemFont(13)
date.textColor = new Color(${JSON.stringify(fg)}, ${dim})

w.addSpacer()

const battRow = w.addStack()
battRow.centerAlignContent()
const battIcon = battRow.addImage(SFSymbol.named("battery.75percent").image)
battIcon.imageSize = new Size(18, 18)
battIcon.tintColor = new Color(${JSON.stringify(fg)}, ${dim})
battRow.addSpacer(6)
const batt = battRow.addText(Math.round(Device.batteryLevel() * 100) + "%")
batt.font = Font.mediumSystemFont(13)
batt.textColor = new Color(${JSON.stringify(fg)}, ${dim})

Script.setWidget(w)
Script.complete()
if (config.runsInApp) { w.presentSmall() }
`;

  return {
    filename: `${sanitize(pack.name)}-Widget.scriptable`,
    content: JSON.stringify(
      {
        always_run_in_app: false,
        icon: { color: 'deep-gray', glyph: 'magic' },
        name: `${pack.name} Widget`,
        script,
        share_sheet_inputs: [],
      },
      null,
      2
    ),
  };
}

// SF Symbols for launcher buttons; fallback handled in-script via app.fill
const LAUNCHER_SYMBOLS = {
  Phone: 'phone.fill', Messages: 'message.fill', Mail: 'envelope.fill',
  Photos: 'photo.fill', Music: 'music.note', Maps: 'map.fill',
  Calendar: 'calendar', Clock: 'clock.fill', Settings: 'gearshape.fill',
  Notes: 'note.text', Reminders: 'checklist', Weather: 'cloud.sun.fill',
  Wallet: 'wallet.pass.fill', Health: 'heart.fill', 'App Store': 'bag.fill',
  Podcasts: 'mic.fill', FaceTime: 'video.fill', Files: 'folder.fill',
  Books: 'book.fill', Fitness: 'figure.run',
  Instagram: 'camera.fill', X: 'xmark', Facebook: 'hand.thumbsup.fill',
  YouTube: 'play.rectangle.fill', WhatsApp: 'phone.bubble.fill',
  Telegram: 'paperplane.fill', Snapchat: 'bolt.fill',
  Spotify: 'music.note.list', Netflix: 'film.fill', Gmail: 'at',
  Chrome: 'globe', Reddit: 'bubble.left.and.bubble.right.fill',
  Discord: 'headphones', Uber: 'car.fill', Amazon: 'shippingbox.fill',
  PayPal: 'banknote.fill', Notion: 'doc.richtext.fill', Slack: 'number',
  Zoom: 'video.fill', TikTok: 'music.quarternote.3',
};

// Launcher widget: medium/large widgets support per-element tap URLs in
// Scriptable, so each button opens a DIFFERENT app — the "actions" a
// Despia SVG widget cannot have. Small falls back to the first target.
export function scriptableLauncherWidget(pack, targets) {
  const s = pack.style;
  const c1 = s.c1;
  const c2 = s.bgType === 'solid' ? shade(s.c1, -0.35) : (s.c2 ?? s.c1);
  const fg = s.glyphColor;
  const list = targets.map((t) => ({
    label: t.label,
    scheme: t.scheme,
    symbol: LAUNCHER_SYMBOLS[t.label] ?? 'app.fill',
  }));

  const script = `// ${pack.name} — launcher widget (tap a button to open that app)
// Generated by Icon Pack Studio. Add as a MEDIUM Scriptable widget.
const TARGETS = ${JSON.stringify(list, null, 2)}

const w = new ListWidget()
const g = new LinearGradient()
g.colors = [new Color(${JSON.stringify(c1)}), new Color(${JSON.stringify(c2)})]
g.locations = [0, 1]
w.backgroundGradient = g

const fg = new Color(${JSON.stringify(fg)})
const dim = new Color(${JSON.stringify(fg)}, 0.65)

if (config.widgetFamily === "small") {
  // small widgets allow only one tap target
  const t = TARGETS[0]
  w.url = t.scheme
  w.addSpacer()
  const sym = SFSymbol.named(t.symbol) ?? SFSymbol.named("app.fill")
  const img = w.addImage(sym.image)
  img.imageSize = new Size(34, 34)
  img.tintColor = fg
  img.centerAlignImage()
  w.addSpacer(8)
  const label = w.addText(t.label)
  label.centerAlignText()
  label.font = Font.mediumSystemFont(12)
  label.textColor = dim
  w.addSpacer()
} else {
  w.addSpacer()
  const row = w.addStack()
  row.centerAlignContent()
  row.addSpacer()
  for (const t of TARGETS) {
    const cell = row.addStack()
    cell.layoutVertically()
    cell.centerAlignContent()
    cell.url = t.scheme          // per-button tap target
    const sym = SFSymbol.named(t.symbol) ?? SFSymbol.named("app.fill")
    const img = cell.addImage(sym.image)
    img.imageSize = new Size(30, 30)
    img.tintColor = fg
    cell.addSpacer(7)
    const label = cell.addText(t.label)
    label.font = Font.mediumSystemFont(11)
    label.textColor = dim
    label.lineLimit = 1
    row.addSpacer()
  }
  w.addSpacer()
}

Script.setWidget(w)
Script.complete()
if (config.runsInApp) { w.presentMedium() }
`;

  return {
    filename: `${sanitize(pack.name)}-Launcher.scriptable`,
    content: JSON.stringify(
      {
        always_run_in_app: false,
        icon: { color: 'deep-gray', glyph: 'rocket' },
        name: `${pack.name} Launcher`,
        script,
        share_sheet_inputs: [],
      },
      null,
      2
    ),
  };
}
