// Generates a .scriptable file — a live, theme-matched widget for the free
// Scriptable app (App Store id 1405459188). Unlike the static photo widgets,
// this one shows real time, date, and battery, styled from the pack palette.
import { shade } from './svg.js';

const sanitize = (s) => s.replace(/[^\w\- ]/g, '').trim().replace(/\s+/g, '-') || 'pack';

export function scriptableWidget(pack) {
  const s = pack.style;
  const c1 = s.c1;
  const c2 = s.bgType === 'solid' ? shade(s.c1, -0.35) : (s.c2 ?? s.c1);
  const fg = s.glyphColor;
  const dim = 0.65;

  const script = `// ${pack.name} — live widget
// Generated by Icon Pack Studio. Install: Scriptable app -> add this script,
// then long-press Home Screen -> add a Scriptable widget -> choose it.
const w = new ListWidget()
w.setPadding(18, 18, 18, 18)

const g = new LinearGradient()
g.colors = [new Color(${JSON.stringify(c1)}), new Color(${JSON.stringify(c2)})]
g.locations = [0, 1]
w.backgroundGradient = g

const time = w.addDate(new Date())
time.applyTimeStyle()
time.font = Font.boldSystemFont(config.widgetFamily === "small" ? 32 : 40)
time.textColor = new Color(${JSON.stringify(fg)})
time.minimumScaleFactor = 0.5

w.addSpacer(4)

const date = w.addDate(new Date())
date.applyDateStyle()
date.font = Font.mediumSystemFont(13)
date.textColor = new Color(${JSON.stringify(fg)}, ${dim})

w.addSpacer()

const battRow = w.addStack()
battRow.centerAlignContent()
const battIcon = battRow.addImage(SFSymbol.named("battery.75percent").image)
battIcon.imageSize = new Size(18, 18)
battIcon.tintColor = new Color(${JSON.stringify(fg)}, ${dim})
battRow.addSpacer(6)
const batt = battRow.addText(Math.round(Device.batteryLevel() * 100) + "%")
batt.font = Font.mediumSystemFont(13)
batt.textColor = new Color(${JSON.stringify(fg)}, ${dim})

Script.setWidget(w)
Script.complete()
if (config.runsInApp) { w.presentSmall() }
`;

  return {
    filename: `${sanitize(pack.name)}-Widget.scriptable`,
    content: JSON.stringify(
      {
        always_run_in_app: false,
        icon: { color: 'deep-gray', glyph: 'magic' },
        name: `${pack.name} Widget`,
        script,
        share_sheet_inputs: [],
      },
      null,
      2
    ),
  };
}
